### ISSUE TITLE
Seek song time

### ISSUE THREAD

**Issue by luciansvnc** [danielmj/AEAudioPlayer#1]
Hi! I found your player on stackoverflow and I am trying to understand how it works. I am struggling to figure it out how did you manage to seek the time of a song. Can you please explain this to me? I am trying to build a slider that controls the time of the song but I can't understand how did you manage to seek the time. Thank you!

**Comment by danielmj** [comment]
Sorry for the delayed response. So in seeking the time you are essentially doing two things: seeking the file pointer and also setting the player's timer. In order to seek the file pointer, you must be using the AVAudioPCMBuffer as your means of feeding the player. If you are using that class you can set the setFramePosition property of you AVAudioFile and it should actually move the file pointer forward. I don't know why this only works with AVAudioPCMBuffer and not when you are just scheduling a AVAudioFile. 

The second part of seeking is to set the players internal timer forward (or backward). To do this you simple instantiate an AVAudioTime object and then call the playAtTime method that the AVAudioPlayerNode has.

I hope this makes sense.

**Comment by luciansvnc** [comment]
Thank you so much for your response! This explanation and your demo app helped me a lot. I finally understood how things are working. Thank you again!

**Comment by abdultcb** [comment]
Hi I am trying to implement the seek functionality. But after applying it returns current time from zero. Below is my code. Please have a look

`- (void)seekTo:(NSTimeInterval )seekTime {
    
    AVAudioTime *nodetime = _player.lastRenderTime;
    AVAudioTime *playerTime = [_player playerTimeForNodeTime:nodetime];
    double sampleRate = playerTime.sampleRate;

    double samplerateInDouble = sampleRate * seekTime;
    AVAudioFramePosition newsampletime = samplerateInDouble;

    float length = [self duration] - seekTime;
    AVAudioFrameCount framestoplay = playerTime.sampleRate * length;

    [self.player stop];
    
    if (framestoplay > 100) {
        [_player scheduleSegment:_file startingFrame:newsampletime frameCount:framestoplay atTime:nil completionHandler:nil];
    }
    
    [_player play];
    
//    AVAudioTime *newSeekTime = [[AVAudioTime alloc] initWithSampleTime:newsampletime atRate:sampleRate];
//    [_player playAtTime:newSeekTime];
//
    
    if (_file != nil)
    {
        fileSampleRate = _file.fileFormat.sampleRate;
        seekNewTimePosition = self.currentTime * _file.fileFormat.sampleRate;
        pausedTime = self.currentTime;
        _file.framePosition = seekTime;
        
    }


}
`

And to get the current time:

`- (NSTimeInterval)currentTime
{
    if(isPaused)
        return pausedTime;
    
    double sampleRate = _file.fileFormat.sampleRate;
    if(sampleRate == 0)
    {
        return 0;
    }
    
    
    NSTimeInterval currentTime = ((NSTimeInterval)[_player playerTimeForNodeTime:_player.lastRenderTime].sampleTime / sampleRate);
    

    
    return currentTime;
}`

**Comment by danielmj** [comment]
Hi abdultcb, does the player actually seek correctly? The problem you are having is with the time not adjusting properly, right?

**Comment by danielmj** [comment]
Its been a long while since I have looked at this framework. I remembered that I ended up using AVAudioPCMBuffer to schedule my frames. I forget exactly why, but it might of had something to do with playAtTime not working right without it. The rough steps that I took were:

1. Initialize the engine if needed
2. Create a new AVAudioFile and set the framePosition property
3. Create an AVAudioTime object using a sampleTime of: `currentLastRenderTime.position-framePosition`
4. Initialize and schedule the AVAudioPCMBuffers with the new AVAudioFile
5. Then playAtTime with the newly created time object.

An alternative is to try to keep track of the time manually.
